/*****************************************************************************/
/*                                                                           */
/* Copyright notice: please read file license.txt in the NetBee root folder. */
/*                                                                           */
/*****************************************************************************/


// IR_OPERATOR(code,		sym,		name)

IR_OPERATOR(OP_DEFFLD,		   "fdef",		 "DEFFLD")
IR_OPERATOR(OP_DEFVAR,		   "vdecl",	         "DEFVAR")
IR_OPERATOR(OP_ASGN,		   "=",		         "ASGN")
IR_OPERATOR(OP_LABEL,		   "lbl",		 "LABEL")
IR_OPERATOR(OP_VAR,		   "var",		 "VAR")
IR_OPERATOR(OP_FIELD,		   "fld",		 "FIELD")
IR_OPERATOR(OP_TEMP,		   "tmp",		 "TEMP")
IR_OPERATOR(OP_CONST,		   "con",		 "CON")
IR_OPERATOR(OP_CINT,		   "ci",		 "CI")
IR_OPERATOR(OP_CHGBORD,		   "chgbord",	         "CHGBORD")
IR_OPERATOR(OP_ADD,		   "+",		         "ADD")
IR_OPERATOR(OP_SUB,		   "-",		         "SUB")
IR_OPERATOR(OP_DIV,		   "/",		         "DIV")	
IR_OPERATOR(OP_MUL,		   "*",		         "MUL")
IR_OPERATOR(OP_NEG,		   "-",		         "NEG")
IR_OPERATOR(OP_SHL,		   "<<",		 "SHL")
IR_OPERATOR(OP_MOD,		   "%",		         "MOD")
IR_OPERATOR(OP_SHR,		   ">>",		 "SHR")	
IR_OPERATOR(OP_XOR,		   "^",		         "XOR")
IR_OPERATOR(OP_AND,		   "&",		         "AND")
IR_OPERATOR(OP_OR,		   "|",		         "OR")
IR_OPERATOR(OP_NOT,		   "~",		         "NOT")
IR_OPERATOR(OP_BOOLAND,		   "&&",		 "AND")
IR_OPERATOR(OP_BOOLOR,		   "||",		 "OR")
IR_OPERATOR(OP_BOOLNOT,		   "!",		         "NOT")
IR_OPERATOR(OP_EQ,		   "==",		 "EQ")
IR_OPERATOR(OP_MATCH,		   "match",	         "MATCH")
IR_OPERATOR(OP_CONTAINS,	   "contains",	         "CONTAINS")
/***********************************************************************/
IR_OPERATOR(OP_RSTR,		   "rs",		 "RS")
/***********************************************************************/
IR_OPERATOR(OP_GE,		  			">=",		 "GE")
IR_OPERATOR(OP_GT,					">",		         "GT")
IR_OPERATOR(OP_LE,				   "<=",		 "LE")
IR_OPERATOR(OP_LT,				   "<",		         "LT")
IR_OPERATOR(OP_NE,					"!=",		 "NE")
IR_OPERATOR(OP_LKINIT,			   "lkinit",	         "LKUP.INIT")
IR_OPERATOR(OP_LKINITTAB,		   "lkinittab",	         "LKUP.INITTAB")
IR_OPERATOR(OP_LKKEYS,			   "lkkeys",	         "LKUP.KEYS")
IR_OPERATOR(OP_LKVALS,			   "lkvals",	         "LKUP.VALS")
IR_OPERATOR(OP_LKADD,			   "lkadd",	         "LKUP.ADD")
IR_OPERATOR(OP_LKSEL,			   "lksel",	         "LKUP.SEL")
IR_OPERATOR(OP_LKHIT,			   "lkhit",	         "LKUP.HIT")
IR_OPERATOR(OP_LKGET,			   "lkget",	         "LKUP.GET")
IR_OPERATOR(OP_LKUPD,			   "lkupd",	         "LKUP.UPD")
IR_OPERATOR(OP_LKDEL,			   "lkdel",	         "LKUP.DEL")
IR_OPERATOR(OP_REGEXINIT,		   "regexinit",          "REGEX.INIT")
IR_OPERATOR(OP_REGEXFND,		   "regexfnd",	         "REGEX.FND")
IR_OPERATOR(OP_REGEXXTR,		   "regexxtr",	         "REGEX.XTR")
IR_OPERATOR(OP_STRINGMATCHINGINIT, "stringmatchinginit", "STRINGMATCHING.INIT") 
IR_OPERATOR(OP_STRINGMATCHINGFND,  "stringmatchingfnd",	 "STRINGMATCHING.FND")
IR_OPERATOR(OP_DATA,		   "data",		 "DATA")
IR_OPERATOR(OP_LKDEFKEY,   	   "lkkdecl",            "LKDEFKEY")  
IR_OPERATOR(OP_LKKEY,	   	   "lkkey",	         "LKKEY")
IR_OPERATOR(OP_LKDEFDATA,  	   "lkddecl",            "LKDEFDATA")  
IR_OPERATOR(OP_LKDATA,	   	   "lkdata",	         "LKDATA")
IR_OPERATOR(OP_LKDEFTABLE, 	   "lktdecl",            "LKDEFTABLE")
IR_OPERATOR(OP_LKTABLE,	   	   "lktable",	         "LKTABLE")

IR_OPERATOR(OP_LAST,		   "---",		 "---")

