#!/usr/bin/python

'This example shows how to work with authentication'

from mininet.log import setLogLevel, info
from mn_wifi.cli import CLI_wifi
from mn_wifi.net import Mininet_wifi
import time
import os
import os.path
import os
from os import path
import subprocess
import socket
import sys

import binascii


def get_hex_key_from_der_key(derfile):
    with open(derfile, mode="rb") as file:
        fileContent = file.read()
    hex_str = binascii.b2a_hex(fileContent)
    return hex_str


def onboard_device(configurator,configurator_clicmd, sta, sta_clicmd, mac_addr,  passwd,ssid) :

    # On enrolee side
    # Generate QR code for the device. Store the qr code id returned by the command.
    key="30770201010420bfb84288edb13a04e05d35c6d976524a9a0656e6265704fc868f7bec971c9f61a00a06082a8648ce3d030107a144034200041e2a1d0e8347ad0d9a501295166439f027899c374f67fc9ef146955e02f8be1b15578382d9b9ea8b91a5bfa96544d069f2a9620cba69bc2bf8230ae0b13d9c64"
    # key generated by Monika
    key="3077020101042026F1181A112402FC90A286B299997A146B5C311C15753211DF9927641702CC58A00A06082A8648CE3D030107A14403420004883D409D7FDED9CBD4800991D615E4F559FCCC0B347D6AFF561FF5EFB60FD94B4E96D46235D0EA99B07B14C032AAD3404EB41DF630215ACDD2C5778FC81A2B57"
    #key=  "26f1181a112402fc90a286b299997a146b5c311c15753211df9927641702cc58"
    #key= "4e96d46235d0ea99b07b14c032aad3404eb41df630215acdd2c5778fc81a2b57" + "883d409d7fded9cbd4800991d615e4f559fccc0b347d6aff561ff5efb60fd94b" + "26f1181a112402fc90a286b299997a146b5c311c15753211df9927641702cc58"
    #key="308187020100301306072a8648ce3d020106082a8648ce3d030107046d306b0201010420ca4e943f1871f31441160396b39dde66c5c76a4fae0e931c9f409a723dbeb058a14403420004cbb996835d7880c43bdd3a0766105dd5175d706180ceeda32802581ccc57cc4cdc24a01ed9276a512f6936d0a8cce8170440437802639baff04a9810c55ebc3a"

    dpp_configurator_id = sta.cmdPrint( sta_clicmd + ' dpp_configurator_add key=' + key + " curve=prime256v1").split('\n')[1]
    #dpp_configurator_id = sta.cmdPrint( sta_clicmd + ' dpp_configurator_add').split('\n')[1]
    info("Configurator: get the configurator key\n")
    dpp_configurator_key = sta.cmd(sta_clicmd + " dpp_configurator_get_key " + str(dpp_configurator_id)).split('\n')[1]
    print("dpp_configurator_key " + dpp_configurator_key)
    #assert dpp_configurator_key==key
    info("enrollee: generate QR code for device public key = {}\n".format(dpp_configurator_key))
    bootstrapping_info_id = sta.cmd( sta_clicmd + " dpp_bootstrap_gen  type=qrcode mac=" + mac_addr  + " key=" + key ).split('\n')[1]
    #Get QR Code of device using the bootstrap info id.
    info("enrollee: get the qr code using the returned bootstrap_info_id\n")
    bootstrapping_uri = "'" + sta.cmd(sta_clicmd + " dpp_bootstrap_get_uri " + str(bootstrapping_info_id)).split('\n')[1] + "'"
    info("enrollee : show the dpp bootstrap info")
    sta.cmdPrint(sta_clicmd + " dpp_bootstrap_info " + bootstrapping_info_id)
    info("bootstrapping_uri = " + bootstrapping_uri + "\n")
    info("enrollee: listen for dpp provisioning request\n")
    #Make device listen to DPP request (The central frequency of channel 1 is 2412) in case if enrollee is a client device.
    sta.cmd(sta_clicmd + " dpp_listen " + str(2412) )
    time.sleep(3)


    info("Configurator:  Enter the sta QR Code in the Configurator.\n")
    bootstrapping_info_id = configurator.cmdPrint(configurator_clicmd + " dpp_qr_code " + bootstrapping_uri).split("\n")[1]
    info("Configurator: Send provisioning request to enrollee. (conf is ap-dpp if enrollee is an AP. conf is sta-dpp if enrollee is a client). configurator_id = {} \n".format(dpp_configurator_id))
    result = configurator.cmd(configurator_clicmd + ' dpp_auth_init peer={} conf=sta-psk ssid={} psk={} configurator={} tcp_addr={} tcp_port=9090'.format(bootstrapping_info_id,ssid,passwd, dpp_configurator_id , "10.0.0.1"))
    result = configurator.cmd(configurator_clicmd + ' dpp_auth_init peer={} conf=sta-psk ssid={} psk={} configurator={} '.format(bootstrapping_info_id,ssid,passwd, dpp_configurator_id ))

    info("Enrollee: save the config file\n")
    sta.cmd(sta_clicmd + " save_config")
    info("Enrollee:  reload the config file\n")
    sta.cmd(sta_clicmd + " reconfigure")
 


def topology():
    "Create a network."
    cwd = os.getcwd()
    net = Mininet_wifi()
    # Note - there is a bug in the DPP code. This only works for short ssids
    ssid = "012a"
    passwd = '12345678'
    cmd = ["wpa_passphrase", ssid, passwd]

    p = subprocess.Popen(cmd,shell=False, stdin= subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    res,err = p.communicate()
    lines = res.split("\n")

    for line in lines:
        if "psk" in line:
            start = line.strip().find("psk=")
            if start == 0:
                psk=line[5:]

    info("Psk = " + psk + "\n")

    info("*** Creating nodes\n")


    ap1 = net.addAccessPoint('ap1', ssid=ssid, mode="g", channel="1",
                             hostapd_flags='-dd > /tmp/hostapd.txt',
                             passwd=passwd, encrypt='wpa2',
                             failMode="standalone", datapath='user')

    
    # sta1 is the configurator
    sta1 = net.addStation('sta1', ssid=ssid, passwd=passwd, encrypt='wpa2', 
           wpasup_flags='-dd -f /tmp/debug1.txt',
           wpasup_globals='ctrl_interface=/var/run/wpa_supplicant1\n'
                          'ctrl_interface_group=0\n')

   


    # sta2 is the enrolee.  Note that it does not have the 
    # PSK and it does not know the access point. 
    # It will be configured by the configurator
    sta2 = net.addStation('sta2',
           wpasup_flags='-dd -f /tmp/debug2.txt',
           wpasup_globals= 'ctrl_interface=/var/run/wpa_supplicant2\n'
                           'ctrl_interface_group=0\n'
                           'update_config=1\n'
                           'pmf=1\n'
                           'dpp_mud_url=https://www.nist.local/nistmud1\n'
                           'dpp_name=MyDpp\n'
                           'dpp_config_processing=2',

           encrypt='wpa2')




    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info("*** Associating Stations\n")
    net.addLink(sta1, ap1)
    net.addLink(sta2, ap1)

    sta1.setMAC("00:00:00:00:00:81","sta1-wlan0")
    sta2.setMAC("00:00:00:00:00:82","sta2-wlan0")

    info("*** Starting network\n")
    net.build()
    ap1.start([])

    info("*** Adding openflow wireless rule : \n ")
    # For wireless isolation hack. Put a normal flow in there so stations
    # can ping each other
    ap1.cmd('ovs-ofctl add-flow ap1 "priority=10,actions=in_port,normal"')
    #sta1.cmdPrint("python sockserver.py&")

    
    # on the configurator 

    cli_cmd = "wpa_cli -p /var/run/wpa_supplicant1 "
    configurator = sta1
    dpp_version = configurator.cmd( cli_cmd + " get_capability dpp").split('\n')[1]
    print("dpp_version is " + dpp_version)
    if dpp_version != "DPP=2":
        sys.exit()

    configurator.cmdPrint( cli_cmd + " dpp_controller_start tcp_port=9090").split('\n')[1]

    configurator.cmd( cli_cmd+" log_level debug")
    info("Configurator: add a configurator object\n")
    dpp_configurator_id = configurator.cmd( cli_cmd + ' dpp_configurator_add ').split('\n')[1]
    info("Configurator: self sign the configurator\n")
    configurator.cmd( cli_cmd + " dpp_configurator_sign conf=sta-psk psk={} ssid={} configurator={}".format(psk,ssid,str(dpp_configurator_id)) )

        

    f = open("sta2_0.staconf","r")
    lines = f.read()
    print("******************************\n")
    print("sta2 staconf BEFORE CONFIGURATION\n")
    print(lines)
    print("******************************")
    f.close()
    
    time.sleep(5)

    onboard_device(sta1,cli_cmd,sta2,"wpa_cli -p /var/run/wpa_supplicant2","00:00:00:00:00:82", psk,ssid.encode('hex'))

    time.sleep(3)

    f = open("sta2_0.staconf","r")
    lines = f.read()
    print("******************************\n")
    print("sta2 staconf AFTER CONFIGURATION\n")
    print(lines)
    print("******************************")
    f.close()

    info("\n*** Try the following at the CLI \n")
    info("sta1 ping sta2 \n")
    info("/tmp/debug*.txt and /tmp/hostapd.txt contain logs \n")
    info("cat /var/log/syslog | grep hostapd shows you if the authentication succeeded\n")
    CLI_wifi(net)

    info("*** Stopping network\n")
    net.stop()


if __name__ == '__main__':
    if path.exists("/tmp/debug1.txt") :
        os.remove("/tmp/debug1.txt")
    if path.exists("/tmp/debug2.txt") :
        os.remove("/tmp/debug2.txt")
    if path.exists("/tmp/hostapd.txt") :
        os.remove("/tmp/hostapd.txt")
    setLogLevel('info')
    topology()
